apiVersion : apps/v1
kind: Deployment
metadata:
  name: asturpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asturpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: asturpipelinesjavascriptdocker 
    spec:
      containers:
        - name: asturpipelinesjavascriptdocker 
          image: mjesusfccontainerregistry.azurecr.io/asturpipelinesjavascriptdocker
          ports:
          - containerPort: 8080